name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up C++ Compiler
      run: sudo apt-get install -y g++

    - name: Build and Run WordPattern.cpp
      run: |
        g++ -o wordPattern Array/wordPattern.cpp
        ./wordPattern

    # Add more steps to compile and run other C++ files as needed
